project:
  type: book
lang: es
book:
  title: "El valor optimo del indice de comportamiento"
  author: "Irasema Pedroza Meza"
  date: "08/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Formulacion.qmd
    - DinamicaModel.qmd
    - costo.qmd
    - acciones.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    crossref:true
  pdf:
    documentclass: scrreprt
    number-sections: true

editor: visual

