project:
  type: book
book:
  title: "El valor optimo del indice de comportamiento"
  author: "Irasema Pedroza Meza"
  date: "08/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Formulacion.qmd
    - DinamicaModel.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

