# Introdución

En la literatura existen una variedad de modelos tipo SIRS en los cuales consideran la vacunación como medida de prevención para el control de enfermedades [@kribs2000simple] . Sin embargo, este medio de control llega a presentar algunas fallas como son: la falla de grado, falla en la toma y falla en la duración [@mclean1993imperfect]. En la modelación de enfermedades respiratorias con ecuaciones diferenciales, se suele considerar que las vacunas tienen una falla tipo de grado [@arino2003global]. Por otro lado, [@PedroMeza], proponen un modelo de ecuaciones diferenciales donde consideran que la vacuna tiene los tre tipos de fallas.

En este ultimo trabajo, proponen un índice de comportamiento ($\psi$) el cual permite medir que tan riguroso pueden seguir las medidas de prevención una vez que son vacunados. En el modelo que proponen este índice solo afecta a los vacunados no inmunes ya que supone que los vacunados que generan inmunidad no se pueden infectar. En este trabajo se desarrollará un proceso de decisión de Markov diseñado para identificar el conjunto de valores de $\psi$ que minimice la cantidad de infectados al finalizar un año [@sutton2018reinforcement].
